### ISSUE TITLE
Github Actions Nice Report?

### ISSUE THREAD

**Issue by randykleinman** [thombashi/pytest-md-report#3]
No problems with the library, just a usage question. Do you have an example of how we could use this in Github Actions and render the markdown report nicely in a PR comment?

**Comment by thombashi** [comment]
@randykleinman 
For example, the following workflow will render the report to the PR when some test failed.

```yaml
name: md-report

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dependencies
        run: pip install --upgrade pytest-md-report
      
      - name: Run tests
        run: pytest tests --md-report --md-report-output md_report.md

      - name: Render report to the PR
        if: failure()
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
        run:
          gh pr comment $PR_NUMBER --body-file md_report.md 
```

Rendering output example:

![image](https://github.com/thombashi/pytest-md-report/assets/15517661/c4cfc893-eadb-4599-a55e-f717fa5753c9)
